apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qainsight-ai

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - rbac.yaml
  - backend-deployment.yaml
  - worker-deployments.yaml
  - frontend-deployment.yaml
  - mcp-deployment.yaml
  - ollama-deployment.yaml
  - services.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: qainsight-ai
      app.kubernetes.io/version: "0.0.1"
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
    includeTemplates: true
